"""add_razorpay_subscription_webhook_models

Revision ID: 15d6654b1413
Revises: 
Create Date: 2026-08-18 18:01:55.494642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15d6654b1413'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(length=320), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('FREE', 'PENDING', 'ACTIVE', 'PAYMENT_FAILED', 'CANCELLED', 'EXPIRED', name='razorpay_subscription_status', native_enum=False, length=32), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_razorpay_subscription_status', 'razorpay_subscription', ['status'], unique=False)
    op.create_index('ix_razorpay_subscription_subscription_id', 'razorpay_subscription', ['razorpay_subscription_id'], unique=False)
    op.create_index(op.f('ix_razorpay_subscription_user_identifier'), 'razorpay_subscription', ['user_identifier'], unique=True)
    op.create_table('razorpay_webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('resulting_status', sa.Enum('FREE', 'PENDING', 'ACTIVE', 'PAYMENT_FAILED', 'CANCELLED', 'EXPIRED', name='razorpay_webhook_event_status', native_enum=False, length=32), nullable=True),
    sa.Column('safe_metadata', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_razorpay_webhook_event_name', 'razorpay_webhook_event', ['event_name'], unique=False)
    op.create_index(op.f('ix_razorpay_webhook_event_razorpay_event_id'), 'razorpay_webhook_event', ['razorpay_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_razorpay_webhook_event_razorpay_event_id'), table_name='razorpay_webhook_event')
    op.drop_index('ix_razorpay_webhook_event_name', table_name='razorpay_webhook_event')
    op.drop_table('razorpay_webhook_event')
    op.drop_index(op.f('ix_razorpay_subscription_user_identifier'), table_name='razorpay_subscription')
    op.drop_index('ix_razorpay_subscription_subscription_id', table_name='razorpay_subscription')
    op.drop_index('ix_razorpay_subscription_status', table_name='razorpay_subscription')
    op.drop_table('razorpay_subscription')
    # ### end Alembic commands ###
